---
# Installation Node.js sur RedHat / Rocky Linux

- name: (RedHat) Mettre à jour les paquets système
  dnf:
    name: '*'
    state: latest
  tags: packages

- name: (RedHat) Installer les paquets requis
  dnf:
    name:
      - git
      - curl
      - "@Development Tools"
    state: present
  tags: packages

- name: (RedHat) Télécharger et exécuter le script NodeSource
  shell: "curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -"
  args:
    creates: /etc/yum.repos.d/nodesource-nodejs.repo
  tags: nodejs

- name: (RedHat) Installer Node.js et npm
  dnf:
    name: nodejs
    state: present
  tags: nodejs
